### ISSUE TITLE
Trained neural network

### ISSUE THREAD

**Issue by SergeyIvanovDevelop** [doguilmak/Drone-Detection-YOLOv7#1]
Could you provide a link to an already trained neural network?
So that you can evaluate the quality of the network without wasting a lot of resources. Thank you.

**Comment by doguilmak** [comment]
Dear Ivanov,

First of all, I would like to thank you for your suggestion, support and interest. For now, we can reach the optimum conclusion about the situation by contacting me at the e-mail address I specified in the README.md file.

Best regards.
